version: '3.1'

services:

  wordpress:
    image: wordpress:6.2
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: umeko-admin
      WORDPRESS_DB_PASSWORD: 'Ch4ng3-M3!'
      WORDPRESS_DB_NAME: peludosyco
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: peludosyco
      MYSQL_USER: umeko-admin
      MYSQL_PASSWORD: 'Ch4ng3-M3!'
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
